# Lyric Video:
# https://youtu.be/INvHma-qltE

if __name__ == "__main__":
    print(("*")*35)
    print("De La Salle Lipa")
    print("Integrated School")
    print("Senior High School")
    print("Grade & Section: ", end="")
    print("Grade 11, S11", "02", sep="-")
    print("Class# - Complete Name: ", end="")
    print("Amazing Grace O. Cabiles")
    print(("*")*35)
    print()
    print(("-")*30)
    print("|Title of your song: ", end="")
    print("Binibini|")
    print("|genre: ", end="")
    print("OPM                  |")
    print("|artist: ", end="")
    print("Zack Tabudlo        |")
    print(("-")*30)
    print()
    print("Binibini\t")
    print("Alam mo ba kung pano nahulog sayo")
    print("Naramdaman lang bigla ng puso\r")
    print("Aking sinta, ikaw lang nagparamdam nito")
    print("Kaya sabihin mo sa akin\r")
    print("Ang tumatakbo sa isip mo\b")
    print("Kung mahal mo na rin ba ako\n")
    print("Isayaw mo ako")
    print("Sa gitna ng ulan, mahal ko\r")
    print("Kapalit man nito'y buhay ko")
    print("Gagawin ang lahat para sayo\r")
    print("Alam kong mahal mo na rin ako\n")
    print("Binibini\t")
    print("Sabi mo noon sakin, ayaw mo pa")
    print("Pero ang yakap ngayo'y kakaiba\r")
    print("Hindi ka ba nalilito, Totoo na bang gusto ko")
    print("Handang labanan ang puso")
    print("Alam kong mahal mo na ko")
    print("Kung ganon, halika na't huwag lumayo\n")
    print("Isayaw mo ako")
    print("Sa gitna ng ulan, mahal ko")
    print("Kapalit man nito'y buhay ko")
    print("Gagawin ang lahat para sayo")
    print("Alam kong mahal mo na rin ako, whoa")
    print("Ooh-\r")
    print("Yeah\n")
    print("Isayaw mo ako")
    print("Sa gitna ng ulan, mahal ko")
    print("Kapalit man nito'y buhay ko")
    print("Gagawin ang lahat para sayo")
    print("Alam kong mahal mo na rin ako\n")
